// sandbox/consumer-app/src/App.tsx
import { useState } from "react";
import { Composer, ResultCard, useComposer, type ComposerAttachment } from "@chai-ui/react";

/**
 * Not a demo of CHAI's design — a packaging smoke test. If this renders a
 * working Composer whose submit produces a ResultCard, the tarballs this
 * app installed (built by ../../scripts/pack-test.sh, not linked via the
 * pnpm workspace) have correct `exports`/`files`/`peerDependencies` and
 * actually work as a real external consumer would experience them. Mirrors
 * the docs site's `useComposer` example on purpose, minus the real engines, so this stays offline (`useComposer` falls back
 * to `mockEngine`).
 */
export function App() {
  const [value, setValue] = useState("");
  const [attachments, setAttachments] = useState<ComposerAttachment[]>([]);
  const { run, submit } = useComposer();

  return (
    <main style={{ maxWidth: 720, margin: "40px auto", fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: "1.1rem" }}>CHAI UI packaging smoke test</h1>
      <p style={{ color: "#666", fontSize: "0.85rem" }}>
        Rendered from real installed tarballs, not the pnpm workspace.
      </p>
      <Composer
        value={value}
        onChange={setValue}
        attachments={attachments}
        onAttachmentsChange={setAttachments}
        useCase={{ kind: "image", label: "Image" }}
        models={[{ id: "mock-model", label: "Mock model", provider: "mock", speed: "fast" }]}
        modelId="mock-model"
        onSubmit={submit}
      />
      {run && <ResultCard results={run.results} prompt={run.request.prompt} onAction={() => {}} />}
    </main>
  );
}

// sandbox/vue-app/src/App.vue
<script setup lang="ts">
// A packaging smoke test, not a demo: if this renders a working Composer
// whose submit produces a ResultCard, the installed tarballs work as a real
// Vue app would use them. Offline: with no engine, useComposer uses mockEngine.
import { ref } from "vue";
import { ChaiProvider, Composer, ResultCard, useComposer, type ComposerAttachment } from "@chai-ui/vue";

const value = ref("");
const attachments = ref<ComposerAttachment[]>([]);
const { run, submit } = useComposer();
</script>

<template>
  <!-- ChaiProvider here only proves it resolves: provide reaches children, so this component's own useComposer doesn't see it. -->
  <ChaiProvider>
    <main style="max-width: 720px; margin: 40px auto; font-family: system-ui">
      <h1 style="font-size: 1.1rem">CHAI UI Vue packaging smoke test</h1>
      <Composer
        v-model="value"
        v-model:attachments="attachments"
        :use-case="{ kind: 'image', label: 'Image' }"
        :models="[{ id: 'mock-model', label: 'Mock model', provider: 'mock', speed: 'fast' }]"
        model-id="mock-model"
        @submit="submit"
      />
      <ResultCard v-if="run" :results="run.results" :prompt="run.request.prompt" @action="() => {}" />
    </main>
  </ChaiProvider>
</template>
